version: "3"

networks:
  job-scrapper-app-network:
    driver: bridge

volumes:
  pg-data:

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    networks:
      - job-scrapper-app-network
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  job-scrapper-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-scrapper-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - job-scrapper-app-network
    environment:
      webdriver.chrome.driver: '/app/chromedriver-win64'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./chromedriver-win64:/app/chromedriver-win64
