spring:
  application:
    name: JobScraperApp
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true

webdriver:
  chrome:
    driver: 'chromedriver-win64/chromedriver.exe'

scratcher:
  base-url: 'https://jobs.techstars.com'